name: Website Deploy, Static to Blob CI

on:
  push:
      branches: [ main, workflowTest, clock-update ]

env:
  PACKAGE_PATH: 'build'  
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: NPM Install and Build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: false #avoids warnings triggering errors
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEPLOYMENT_CREDENTIALS }}        
    
    - name: Upload to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: ${{ env.PACKAGE_PATH }}
    
    - name: Upload Static Site Backup
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{secrets.AZURE_STORAGE_ACCT_NAME}} -d '$web' -s build

    - name: Logout
      run: |
          az logout
